"""PDF report generator using ReportLab."""
from __future__ import annotations

import os
from datetime import datetime
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable,
)

from ultrasonic_weld_master.core.models import WeldRecipe, ValidationResult


_RISK_COLORS = {"low": colors.green, "medium": colors.orange, "high": colors.red, "critical": colors.darkred}


class PdfGenerator:
    def export(self, recipe: WeldRecipe, validation: Optional[ValidationResult] = None,
               output_dir: str = ".") -> str:
        filename = "report_%s_%s.pdf" % (recipe.recipe_id, datetime.now().strftime("%Y%m%d_%H%M%S"))
        path = os.path.join(output_dir, filename)

        doc = SimpleDocTemplate(path, pagesize=A4,
                                leftMargin=20 * mm, rightMargin=20 * mm,
                                topMargin=15 * mm, bottomMargin=15 * mm)
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle("ReportTitle", parent=styles["Title"], fontSize=18, spaceAfter=12)
        heading_style = ParagraphStyle("SectionHead", parent=styles["Heading2"], fontSize=13, spaceAfter=6)

        elements = []

        # Title
        elements.append(Paragraph("Ultrasonic Welding Parameter Report", title_style))
        elements.append(Spacer(1, 4 * mm))

        # Section 1: Summary
        elements.append(Paragraph("1. Summary", heading_style))
        summary_data = [
            ["Recipe ID", recipe.recipe_id],
            ["Application", recipe.application],
            ["Date", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ]
        for k, v in recipe.inputs.items():
            summary_data.append([k.replace("_", " ").title(), str(v)])
        elements.append(self._make_table(summary_data, col_widths=[60 * mm, 100 * mm]))
        elements.append(Spacer(1, 6 * mm))

        # Section 2: Parameters
        elements.append(Paragraph("2. Welding Parameters", heading_style))
        param_data = [["Parameter", "Value", "Safe Min", "Safe Max"]]
        for param, value in recipe.parameters.items():
            sw = recipe.safety_window.get(param)
            sw_min = str(sw[0]) if sw and len(sw) >= 2 else "-"
            sw_max = str(sw[1]) if sw and len(sw) >= 2 else "-"
            param_data.append([param, str(value), sw_min, sw_max])
        elements.append(self._make_table(param_data, header=True,
                                          col_widths=[45 * mm, 35 * mm, 35 * mm, 35 * mm]))
        elements.append(Spacer(1, 6 * mm))

        # Section 3: Risk Assessment
        elements.append(Paragraph("3. Risk Assessment", heading_style))
        risk_data = [["Risk Type", "Level"]]
        for k, v in recipe.risk_assessment.items():
            risk_data.append([k.replace("_", " ").title(), v.upper()])
        t = self._make_table(risk_data, header=True, col_widths=[80 * mm, 80 * mm])
        elements.append(t)
        elements.append(Spacer(1, 6 * mm))

        # Section 4: Recommendations
        elements.append(Paragraph("4. Recommendations", heading_style))
        for rec in recipe.recommendations:
            elements.append(Paragraph("- " + rec, styles["Normal"]))
        elements.append(Spacer(1, 6 * mm))

        # Section 5: Validation
        if validation:
            elements.append(Paragraph("5. Validation Results", heading_style))
            elements.append(Paragraph("Overall: %s" % validation.status.value.upper(), styles["Normal"]))
            for msg in validation.messages:
                elements.append(Paragraph("  " + msg, styles["Normal"]))
            elements.append(Spacer(1, 6 * mm))

        # Footer line
        elements.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
        elements.append(Paragraph("Generated by UltrasonicWeldMaster v0.1.0", styles["Normal"]))

        doc.build(elements)
        return path

    def _make_table(self, data, header=False, col_widths=None):
        t = Table(data, colWidths=col_widths)
        style_cmds = [
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]
        if header:
            style_cmds.extend([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4472C4")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ])
        t.setStyle(TableStyle(style_cmds))
        return t
